### ISSUE TITLE
Crashes in DSS section sometimes

### ISSUE THREAD

**Issue by katemaguire** [japelj/archival#1]
I have tried "TEST 13:51:18.15 -22:53:59.1 2019-03-11.70" and the script completes and makes the necessary output files. However, when I tried "TEST  04:53:18.15 -32:50:50.1 2019-03-11.70" the script fails at line 1205:

python /Users/maguireadmin/ENGRAVE_soft/archival/archival.py -i input_list.txt

ARCHIVAL

Input file and content:
	 input_list.txt
		 TEST  04:53:18.15 -32:50:50.1 2019-03-11.70
Start program
Note that the execution speed depends on the servers of the pages from where the content is parsed.
TEST
	Visibility
	... plot saved to: output/TEST/TEST.gif
	Extinction
lxml not found, please install it
	Simbad
	... Search radius:  20  arcsec
	... Number of sources:  1
	TNS
	... Search radius: 20  arcsec
	... Start date: 2001-01-01
	... Number of sources: 1
	GLADE
	... Luminosity distance is not provided - a simple search within a radius of 15 arcsec
	... Number of sources: 1
	Minor planets
	... Search radius: 5  arcmin
	... Magnitude limit: 24.0 mag
	... Epoch: 2019-03-11.70
	... Minor planets found: 0
	Retrieving Pan-STARRS cutout
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=73.325625&dec=-32.84725&size=1200&format=fits&filters=r
|===========================================================================================================================================================|  67 / 67  (100.00%)         0s
	... Image not available
	Retrieving DSS cutout
	... image saved to: output/TEST/TEST_dss_red.fits
Unknown property fontdict
	Additional info

Building an html summary page:  output/summary.html
Traceback (most recent call last):
  File "/Users/maguireadmin/ENGRAVE_soft/archival/archival.py", line 1355, in <module>
    main()
  File "/Users/maguireadmin/ENGRAVE_soft/archival/archival.py", line 1348, in main
    makehtml(nam,parin,vis,ext,sim,wei,mpp,gla,ld,pan,dss,add,fol,mpp2)
  File "/Users/maguireadmin/ENGRAVE_soft/archival/archival.py", line 1205, in makehtml
    doc.stag('img', src=name[i]+'/'+dss[i])
TypeError: must be str, not int

**Comment by japelj** [comment]
Hi Kate, I can't reproduce the error on my machine (runs through smoothly). Can you please send me the output image (output/TEST/TEST_dss_red.fits)? Also, can you tell me what is your matplotlib version? Thanks!
